-- create sequence for table CLIENTS
CREATE SEQUENCE SEQUENCE_CLIENTS INCREMENT BY 1 START WITH 1 MAXVALUE 1000 MINVALUE 1;


-- create sequence for table EMPLOYEES
CREATE SEQUENCE SEQUENCE_EMPLOYEES INCREMENT BY 1 START WITH 1 MAXVALUE 300 MINVALUE 1;



-- create sequence for table CREDITS
CREATE SEQUENCE SEQUENCE_CREDITS INCREMENT BY 1 START WITH 1 MAXVALUE 10000 MINVALUE 1;




-- create sequence for table DEPOSITS
CREATE SEQUENCE SEQUENCE_DEPOSITS INCREMENT BY 1 START WITH 1 MAXVALUE 10000 MINVALUE 1;





-- create sequence for table BRANCHES
CREATE SEQUENCE SEQUENCE_BRANCHES INCREMENT BY 1 START WITH 1 MAXVALUE 10 MINVALUE 1;





-- create sequence for table CURRENCY
CREATE SEQUENCE SEQUENCE_CURRENCY INCREMENT BY 1 START WITH 1 MAXVALUE 10 MINVALUE 1;