CREATE TABLE BRANCHES (
BRANCHEID NUMBER generated by default as identity
(start with 1
increment by 1
maxvalue 100
NOCYCLE),
CITY VARCHAR2(30) not null,
ADDRESS VARCHAR2(50) not null,
EMPLOYEEID NUMBER not null,
PRIMARY KEY (BRANCHEID));