CREATE TABLE CLIENTS (
CLIENTID NUMBER generated by DEFAULT as identity
(start with 1
increment by 1
maxvalue 1000
NOCYCLE),
FNAME VARCHAR2(20) not null,
LNAME VARCHAR2(30) not null,
AGE NUMBER not null,
PROFESSIONAL VARCHAR2(20) not null,
IBAN VARCHAR2(34) not null,
PRIMARY KEY (CLIENTID));