CREATE TABLE DEPOSITS (
DEPOSITID NUMBER generated by DEFAULT as identity
(start with 1
increment by 1
maxvalue 1000
NOCYCLE),
TYPE VARCHAR2(20) not null,
SYZE NUMBER not null,
TERM NUMBER not null,
INTEREST_RATE DECIMAL not null,
CURRENCYID NUMBER not null,
CLIENTID NUMBER not null,
PRIMARY KEY (DEPOSITID));