CREATE TABLE EMPLOYEES (
EMPLOYEEID NUMBER generated by DEFAULT as identity
(start with 1
increment by 1
maxvalue 300
NOCYCLE),
FNAME VARCHAR2(20) not null,
LNAME VARCHAR2(30) not null,
AGE NUMBER not null,
POSITION VARCHAR2(20) not null,
SALARY DECIMAL not null,
PRIMARY KEY (EMPLOYEEID));